/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "surface-variant": "#d3e4fe",
            "primary": "#000000",
            "inverse-surface": "#213145",
            "on-surface-variant": "#45464d",
            "on-secondary-fixed": "#002113",
            "surface-container-high": "#dce9ff",
            "tertiary-container": "#001a42",
            "surface-bright": "#f8f9ff",
            "error": "#ba1a1a",
            "surface-container-lowest": "#ffffff",
            "tertiary": "#000000",
            "surface-container-highest": "#d3e4fe",
            "inverse-primary": "#bec6e0",
            "on-secondary-fixed-variant": "#005236",
            "on-tertiary-container": "#3980f4",
            "inverse-on-surface": "#eaf1ff",
            "on-surface": "#0b1c30",
            "outline": "#76777d",
            "secondary": "#006c49",
            "on-background": "#0b1c30",
            "secondary-fixed-dim": "#4edea3",
            "on-primary-fixed-variant": "#3f465c",
            "on-primary": "#ffffff",
            "primary-fixed": "#dae2fd",
            "surface-tint": "#565e74",
            "surface-container": "#e5eeff",
            "on-error": "#ffffff",
            "background": "#f8f9ff",
            "on-secondary": "#ffffff",
            "on-primary-fixed": "#131b2e",
            "outline-variant": "#c6c6cd",
            "on-tertiary": "#ffffff",
            "secondary-fixed": "#6ffbbe",
            "surface-container-low": "#eff4ff",
            "tertiary-fixed": "#d8e2ff",
            "primary-container": "#131b2e",
            "primary-fixed-dim": "#bec6e0",
            "error-container": "#ffdad6",
            "tertiary-fixed-dim": "#adc6ff",
            "on-secondary-container": "#00714d",
            "on-tertiary-fixed": "#001a42",
            "surface": "#f8f9ff",
            "secondary-container": "#6cf8bb",
            "surface-dim": "#cbdbf5",
            "on-error-container": "#93000a",
            "on-primary-container": "#7c839b",
            "on-tertiary-fixed-variant": "#004395"
        },
        "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        "spacing": {
            "sm": "8px",
            "xl": "32px",
            "xs": "4px",
            "margin": "40px",
            "gutter": "24px",
            "unit": "4px",
            "lg": "24px",
            "max-width": "1280px",
            "md": "16px"
        },
        "fontFamily": {
            "headline-xl": ["Manrope", "sans-serif"],
            "headline-lg": ["Manrope", "sans-serif"],
            "label-caps": ["Inter", "sans-serif"],
            "body-lg": ["Inter", "sans-serif"],
            "body-md": ["Inter", "sans-serif"],
            "body-sm": ["Inter", "sans-serif"],
            "data-mono": ["Inter", "sans-serif"],
            "headline-md": ["Manrope", "sans-serif"],
            "manrope": ["Manrope", "sans-serif"],
            "inter": ["Inter", "sans-serif"]
        },
        "fontSize": {
            "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
            "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
            "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
            "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
            "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
            "data-mono": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
            "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
        }
    }
  },
  plugins: [],
}
