// AUTO-GENERATED by Universal QA Agent
// App: process.env.APP_URL
// Generated: 2024-05-01
// Total scenarios: 4
// Safe mode: process.env.SAFE_MODE
// Destructive security tests: process.env.RUN_DESTRUCTIVE_SECURITY_TESTS

import { test, expect, Page } from '@playwright/test';
import { Selectors } from './selectors';

const APP_URL = process.env.APP_URL ?? 'http://localhost:5173';
const RUN_DESTRUCTIVE_SECURITY_TESTS = process.env.RUN_DESTRUCTIVE_SECURITY_TESTS === 'true';

async function attachConsoleCapture(page: Page) {
  const errors: string[] = [];
  page.on('console', msg => {
    // Only capture specific console errors to avoid noise
    if (msg.type() === 'error' && !msg.text().includes('favicon')) errors.push(msg.text());
  });
  page.on('pageerror', err => {
    errors.push(err.message);
  });
  return {
    errors,
    assertNoErrors: () => expect(errors).toEqual([]),
  };
}

test.describe('DASHBOARD', () => {
  test.describe('Happy Path', () => {
    test('DASHBOARD-HP-001 — App loads and shows Zenith Rewards', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto(APP_URL);
      await expect(Selectors.nav.heading(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });

    test('DASHBOARD-HP-002 — Portfolio Summary is visible', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto(APP_URL);
      await expect(Selectors.dashboard.portfolioSummary(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });

    test('DASHBOARD-HP-003 — Stub label is visible', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto(APP_URL);
      await expect(Selectors.dashboard.stubLabel(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });
  });
});

test.describe('NAV', () => {
  test.describe('Negative', () => {
    test('NAV-NEG-001 — Unknown route shows safe fallback (app renders main layout)', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto(`${APP_URL}/unknown-route`);
      await expect(Selectors.nav.heading(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });
  });
});

test.describe('SECURITY', () => {
  test('SEC-HP-001 — Headers are checked', async ({ page }) => {
    const response = await page.goto(APP_URL);
    expect(response).not.toBeNull();
    const headers = response?.headers() || {};
  });
});
