// AUTO-GENERATED by Universal QA Agent — Phase 2
// Do not edit manually. Re-run agent to regenerate.

import { Page } from '@playwright/test';

export const Selectors = {
  nav: {
    heading: (page: Page) => page.locator('h1').filter({ hasText: 'Zenith Rewards' }),
  },
  dashboard: {
    portfolioSummary: (page: Page) => page.locator('h2').filter({ hasText: 'Portfolio Summary' }),
    stubLabel: (page: Page) => page.locator('text=Sandbox / Stub Mode'),
  }
};
